[package]
name = "folo_ffi"
description = "Utilities for working with FFI logic; exists for internal use in Folo packages; no stable API surface"
publish = true
version = "0.1.3"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
doc = false

[features]
default = []

[dependencies]

[dev-dependencies]
mutants = { workspace = true }

[lints]
workspace = true
