[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Sander Saares <sander@saares.eu>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/folo-rs/folo"
rust-version = "1.85"

[profile.release]
# This ensures we have high quality data with full symbols when profiling.
debug = "full"

[workspace.dependencies]
# The packages we publish.
cpulist = { version = "0.0.1-pre.2", path = "crates/cpulist" }
linked = { version = "0.0.1-pre.3", path = "crates/linked" }
linked_macros = { version = "0.0.1-pre.3", path = "crates/linked_macros" }
linked_macros_impl = { version = "0.0.1-pre.3", path = "crates/linked_macros_impl" }
many_cpus = { version = "0.0.1-pre.2", path = "crates/many_cpus" }
many_cpus_benchmarking = { version = "0.0.1-pre.3", path = "crates/many_cpus_benchmarking" }

# The packages we consume.
axum = "0.8"
# Using Git reference here because the published crate is out of date and lacks proper graph support.
criterion = { version = "0.5", git = "https://github.com/bheisler/criterion.rs.git" }
darling = "0.20"
derive_more = "2.0"
fake_headers = "0.0"
frozen-collections = "0.3"
hash_hasher = "2.0"
http = "1.2"
itertools = "0.14"
libc = "0.2"
mockall = "0.13"
negative-impl = "0.1"
nonempty = "0.11"
oneshot = "0.1"
paste = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
rand = "0.9"
scc = "2.3"
scopeguard = "1.2"
seq-macro = "0.3"
static_assertions = "1"
syn = "2.0"
thiserror = "2.0"
tokio = "1.43"
windows = "0.58"
