[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Sander Saares <sander@saares.eu>"]
edition = "2024"
license = "MIT"
rust-version = "1.85"
version = "0.1.0"

[profile.release]
debug = "full"
