[workspace]
# TEMP: it currently complains for some unclear reason.
allow_dirty = true

# At this point in pre-alpha time, changelogs are very messy and useless.
changelog_update = false

# All we care about is crates.io, Git releases are not used.
git_release_enable = false

[[package]]
name = "linked"

# Changelogs of these two are merged into the `linked` package as the others are "invisible" packages.
changelog_include = ["linked_macros", "linked_macros_impl"]

# All the `linked*` packages are published under the same version, as they are
# all the "logically same" package, just separated for cargotechnical reasons.
version_group = "linked"

[[package]]
name = "linked_macros"

# This package is invisible, changes are recorded in `linked` changelog instead.
changelog_update = false

# All the `linked*` packages are published under the same version, as they are
# all the "logically same" package, just separated for cargotechnical reasons.
version_group = "linked"

[[package]]
name = "linked_macros_impl"

# This package is invisible, changes are recorded in `linked` changelog instead.
changelog_update = false

# All the `linked*` packages are published under the same version, as they are
# all the "logically same" package, just separated for cargotechnical reasons.
version_group = "linked"

[[package]]
name = "cargo-detect-package"

# Blocked by https://github.com/release-plz/release-plz/issues/2317
release = false