/// Defines a dynamic cast method that extends pooled item handles, allowing casting
/// of the reference to a trait object.
///
/// This macro generates a trait that provides a method to cast a pooled value
/// from an unknown concrete type to a trait object, while preserving the reference counting
/// and pool management semantics, returning a handle that dereferences to the trait object
/// instead of the original concrete type.
///
/// The generated cast method allows conversion from `Pooled<T>` to `Pooled<dyn Trait>`
/// (and similarly for `LocalPooled` and `RawPooled`) where `T` implements the trait.
///
/// # Parameters
///
/// - `trait_name`: The trait name (e.g., `Display`, `SendUnitFuture`). The method name
///   is automatically derived by converting this to `snake_case` with a `cast_` prefix.
///
/// For complex trait bounds, define a trait alias first, to simplify the trait to a single name,
/// then use this macro with the trait alias name.
///
/// # Generated Items
///
/// For `define_pooled_dyn_cast!(Display)`, this macro generates:
///
/// - Trait `PooledCastDisplay` with method `cast_display()`, at `pub(crate)` visibility
/// - Implementations for `Pooled<T>`, `LocalPooled<T>`, and `RawPooled<T>`
///
/// # Examples
///
/// Basic trait casting:
///
/// ```rust
/// use std::fmt::Display;
///
/// use blind_pool::{BlindPool, define_pooled_dyn_cast};
///
/// // Define the cast operation.
/// define_pooled_dyn_cast!(Display);
///
/// let pool = BlindPool::new();
/// let pooled = pool.insert(42_u32);
///
/// // Cast to trait object while preserving reference counting.
/// let display_pooled = pooled.cast_display();
///
/// // Can now store in a struct.
/// struct Foo {
///     value: blind_pool::Pooled<dyn Display>,
/// }
///
/// let foo = Foo {
///     value: display_pooled,
/// };
/// ```
///
/// Complex trait bounds using trait aliases:
///
/// ```rust
/// use std::future::Future;
///
/// use blind_pool::{BlindPool, define_pooled_dyn_cast};
///
/// // Define a trait alias for complex bounds.
/// // Minimum accepted visibility is `pub(crate)`.
/// pub(crate) trait UnitFuture: Future<Output = ()> + Send {}
/// impl<T> UnitFuture for T where T: Future<Output = ()> + Send {}
///
/// // Define cast using the trait alias.
/// define_pooled_dyn_cast!(UnitFuture);
///
/// let pool = BlindPool::new();
/// let pooled = pool.insert(async {});
///
/// // Cast to trait object (method name derived from trait alias).
/// let future_pooled = pooled.cast_unit_future();
///
/// struct TaskManager {
///     tasks: Vec<blind_pool::Pooled<dyn UnitFuture>>,
/// }
/// ```
#[macro_export]
macro_rules! define_pooled_dyn_cast {
    ($trait_name:ident) => {
        ::paste::paste! {
            /// Extension trait for casting pooled values to trait objects.
            ///
            /// This trait is generated by the [`define_pooled_dyn_cast!`] macro and provides
            /// a method to cast pooled values to the specified trait object type.
            pub(crate) trait [<PooledCast $trait_name>]<T> {
                /// Casts this pooled value to a trait object.
                ///
                /// This method converts a pooled value from an unknown concrete type to a
                /// trait object while preserving the reference counting and pool management
                /// semantics.
                ///
                /// The cast is performed through safe reference coercion - if the concrete
                /// type does not implement the required trait, compilation will fail.
                fn [<cast_ $trait_name:snake>](self) -> Self::Output;

                /// The output type after casting.
                type Output;
            }

            impl<T> [<PooledCast $trait_name>]<T> for $crate::Pooled<T>
            where
                T: $trait_name + 'static,
            {
                type Output = $crate::Pooled<dyn $trait_name>;

                fn [<cast_ $trait_name:snake>](self) -> Self::Output {
                    self.__private_cast_dyn_with_fn(|x| x as &dyn $trait_name)
                }
            }

            impl<T> [<PooledCast $trait_name>]<T> for $crate::LocalPooled<T>
            where
                T: $trait_name + 'static,
            {
                type Output = $crate::LocalPooled<dyn $trait_name>;

                fn [<cast_ $trait_name:snake>](self) -> Self::Output {
                    self.__private_cast_dyn_with_fn(|x| x as &dyn $trait_name)
                }
            }
            
            /// Extension trait for casting raw-pooled values to trait objects.
            ///
            /// This trait is generated by the [`define_pooled_dyn_cast!`] macro and provides
            /// a method to cast raw-pooled values to the specified trait object type.
            pub(crate) trait [<RawPooledCast $trait_name>]<T> {
                /// Casts this raw pooled value to a trait object.
                ///
                /// This method converts a pooled value from an unknown concrete type to a
                /// trait object while preserving the reference counting and pool management
                /// semantics.
                ///
                /// The cast is performed through safe reference coercion - if the concrete
                /// type does not implement the required trait, compilation will fail.
                /// 
                /// # Safety
                /// 
                /// The caller is responsible for ensuring that the raw pooled object
                /// handle points to an item that is still present in the pool.
                /// 
                /// The caller must guarantee that the target object is in a state where it is
                /// valid to create a shared reference to it (i.e. no concurrent `&mut` exclusive
                /// references exist.)
                unsafe fn [<cast_ $trait_name:snake>](self) -> Self::Output;

                /// The output type after casting.
                type Output;
            }
            
            impl<T> [<RawPooledCast $trait_name>]<T> for $crate::RawPooled<T>
            where
                T: $trait_name + 'static,
            {
                type Output = $crate::RawPooled<dyn $trait_name>;

                unsafe fn [<cast_ $trait_name:snake>](self) -> Self::Output {
                    // SAFETY: Forwarding safety guarantees from the caller.
                    unsafe {
                        self.__private_cast_dyn_with_fn(|x| x as &dyn $trait_name)
                    }
                }
            }
        }
    };
}
