graph TD
    subgraph Thread1[Thread 1]
        Task1a[Local task] -->|deref| ThreadLocal1a[ThreadLocal]
        Task1b[Local task] -->|deref| ThreadLocal1b[ThreadLocal]

        ThreadLocal1a --> SharedOwnership((Shared<br/>ownership))
        ThreadLocal1b --> SharedOwnership

        SharedOwnership --> Instance1[Linked object instance]
    end

    subgraph Thread2[Thread 2]
        Task2a[Local task] -->|deref| ThreadLocal2a[ThreadLocal]
        Task2b[Local task] -->|deref| ThreadLocal2b[ThreadLocal]

        ThreadLocal2a --> SharedOwnership2((Shared<br/>ownership))
        ThreadLocal2b --> SharedOwnership2

        SharedOwnership2 --> Instance2[Linked object instance]
    end

    Instance1 --> SharedState[Family state]
    Instance2 --> SharedState