//! Serializes a derived [`Table`] into the committed `cbh_stats` source file, and the write/check
//! contract over that one file.
//!
//! It mirrors `cargo-bench-history-figures`' asset contract, narrowed to a single generated Rust
//! source: [`write`] regenerates the file, [`check`] re-renders into memory and reports drift so a
//! stale table fails a test. The rendered file opens with a provenance header recording everything
//! needed to reproduce it, so a reviewer can regenerate it and get identical bytes.

use std::fmt::Write as _;
use std::path::Path;
use std::{fs, io};

use crate::derive::Table;
use crate::{
    ANCHOR_LEVEL, DKW_ALPHA, EXACT_MAX_N, LADDER_FLOOR, LADDER_RATIO, MAX_SERIES_LEN,
    MIN_SERIES_LEN, PRODUCTION_SAMPLES,
};

/// Where the generated table lives, relative to the workspace root.
///
/// `cbh_stats::selection` includes it from here, so this path is the contract between this
/// generator and that crate. It is a constant in the library, not the binary, so the freshness
/// test can reach it without the CLI.
pub const TABLE_PATH: &str = "packages/cbh_stats/src/selection/table.rs";

/// Regenerates the committed table at `root`, overwriting it.
pub fn write(root: &Path, table: &Table) -> io::Result<()> {
    let location = root.join(TABLE_PATH);
    if let Some(parent) = location.parent() {
        fs::create_dir_all(parent).map_err(|error| wrap_io(&error, "create directory", parent))?;
    }
    fs::write(&location, render(table)).map_err(|error| wrap_io(&error, "write", &location))
}

/// Compares the committed table at `root` against freshly rendered content.
///
/// Returns `None` when they match and a human-readable report otherwise, with the same message
/// shape the figures crate uses so a drifted table reads the same in CI.
pub fn check(root: &Path, table: &Table) -> io::Result<Option<String>> {
    let location = root.join(TABLE_PATH);
    let rendered = render(table);
    match fs::read_to_string(&location) {
        Ok(existing) if existing == rendered => Ok(None),
        Ok(_) => Ok(Some(format!(
            "The committed calibration table is out of date: {TABLE_PATH} differs from what the \
             generator now produces. Run `just bench-history-calibration-write` to regenerate it, \
             then review the diff — a change means the detector's procedure or a calibration \
             constant changed.\n"
        ))),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(Some(format!(
            "The committed calibration table is missing: {TABLE_PATH} has not been generated yet. \
             Run `just bench-history-calibration-write` to create it.\n"
        ))),
        Err(error) => Err(wrap_io(&error, "read", &location)),
    }
}

/// Renders `table` into the committed Rust source file's exact bytes.
#[must_use]
pub(crate) fn render(table: &Table) -> String {
    let levels = table.levels();
    let rows = table.rows();
    let num_levels = levels.len();

    let mut source = String::new();
    source.push_str(&header(num_levels, rows.len()));

    writeln!(source, "pub const MIN_SERIES_LEN: usize = {MIN_SERIES_LEN};")
        .expect("writing to a String never fails");
    writeln!(source, "pub const MAX_SERIES_LEN: usize = {MAX_SERIES_LEN};")
        .expect("writing to a String never fails");
    writeln!(source, "pub const NUM_LEVELS: usize = {num_levels};")
        .expect("writing to a String never fails");
    source.push('\n');

    source.push_str("pub static ADJUSTED_LEVELS: [f64; NUM_LEVELS] = ");
    push_row(&mut source, levels);
    source.push_str(";\n\n");

    writeln!(
        source,
        "pub static CRITICAL_TAINTED_P: [[f64; NUM_LEVELS]; {}] = [",
        rows.len()
    )
    .expect("writing to a String never fails");
    for row in rows {
        source.push_str("    ");
        push_row(&mut source, row);
        source.push_str(",\n");
    }
    source.push_str("];\n");

    source
}

/// The provenance header: everything a reviewer needs to reproduce the file byte-for-byte.
fn header(num_levels: usize, num_rows: usize) -> String {
    let mut header = String::new();
    // The file is excluded from rustfmt via the `ignore` list in `unstable-rustfmt.toml`, so the
    // rendered data bytes stay identical to what `check` compares against. A whole-file
    // `#![rustfmt::skip]` inner attribute cannot be used because it is unstable on the stable
    // toolchain that compiles this crate.
    header.push_str(
        "#![allow(clippy::unreadable_literal, reason = \"generated float table; digit-group \
         separators would bloat it without aiding a reader\")]\n",
    );
    header.push_str("//! Selection-adjusted change-point p-value calibration table.\n");
    header.push_str("//!\n");
    header.push_str(
        "//! Generated by the `cargo-bench-history-calibration` crate. Do not edit by hand: run\n\
         //! `just bench-history-calibration-write` to regenerate, and see that crate's docs and\n\
         //! `cargo-bench-history`'s design appendix for the method.\n",
    );
    header.push_str("//!\n");
    header.push_str("//! # Provenance\n");
    header.push_str("//!\n");
    write!(
        header,
        "//! * Procedure: Pettitt location over every interior split, `min_regime` rejection, then\n\
         //!   the two-sided Mann–Whitney p-value at the located split — the change-point detector's\n\
         //!   own procedure, evaluated on rank orderings (ties absent, so the tie term is zero).\n\
         //! * Rows: one per series length {MIN_SERIES_LEN}..={MAX_SERIES_LEN} ({num_rows} rows), no gaps.\n\
         //! * Small rows (n <= {EXACT_MAX_N}): exhaustive enumeration of all n! orderings — exact, no margin.\n\
         //! * Larger rows: {PRODUCTION_SAMPLES} Monte Carlo orderings via the workspace splitmix64\n\
         //!   generator, seeded per row by FNV-1a over a fixed label.\n\
         //! * Conservativeness: a one-sided Dvoretzky–Kiefer–Wolfowitz band added to each sampled\n\
         //!   CDF, Bonferroni-split across the Monte Carlo rows at family level {DKW_ALPHA}, so no row\n\
         //!   under-corrects (over the generation randomness). Where the band cannot certify a level,\n\
         //!   the ladder stops and deeper outcomes report its floor.\n\
         //! * Grid: {num_levels} adjusted levels, geometric ratio {LADDER_RATIO}, anchored exactly on\n\
         //!   {ANCHOR_LEVEL}, spanning down to {LADDER_FLOOR}, with an explicit 1.0 top rung.\n\
         //! * Rounding: each value is the shortest decimal that round-trips to the same f64, with a\n\
         //!   trailing `.0` on integers so every element parses as f64.\n"
    )
    .expect("writing to a String never fails");
    header.push('\n');
    header
}

/// Appends `values` as an `f64` array literal on one line.
fn push_row(source: &mut String, values: &[f64]) {
    source.push('[');
    for (position, &value) in values.iter().enumerate() {
        if position > 0 {
            source.push_str(", ");
        }
        source.push_str(&render_f64(value));
    }
    source.push(']');
}

/// Renders one `f64` as the shortest decimal that round-trips, guaranteed to parse as `f64`.
///
/// Rust's `Display` for `f64` emits the shortest round-tripping decimal and never uses exponent
/// form, so the only adjustment needed is a trailing `.0` on a value that came out as a bare
/// integer (`0`, `1`), which would otherwise be an integer literal in an `f64` array.
fn render_f64(value: f64) -> String {
    let mut rendered = format!("{value}");
    if !rendered.contains('.') {
        rendered.push_str(".0");
    }
    rendered
}

/// Attaches the attempted operation and path to a filesystem failure.
fn wrap_io(error: &io::Error, operation: &'static str, path: &Path) -> io::Error {
    io::Error::new(
        error.kind(),
        format!("failed to {operation} {}: {error}", path.display()),
    )
}
