[package]
name = "region_cached"
description = "Region-cached static variables that store intermediate clones of values in the local memory region, facilitating high data locality on many-processor systems."
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
many_cpus = { path = "../many_cpus" }

[dev-dependencies]
# Using Git reference here because the published crate is out of date and lacks proper graph support.
criterion = { git = "https://github.com/bheisler/criterion.rs.git" }
mockall = "0.13"
static_assertions = "1"


[[bench]]
name = "region_cached"
harness = false
