[package]
name = "cpu_time_tracker"
description = "CPU time tracking utilities for benchmarks and performance analysis"
publish = true
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cpu-time = "1.0.0"

[dev-dependencies]
criterion = { workspace = true }
mutants = { workspace = true }

[[bench]]
name = "cpu_time_tracker_bench_example"
harness = false

[lints]
workspace = true
