name: Windows Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-validation:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup environment
      uses: ./.github/actions/setup-environment
      with:
        cache-key-suffix: windows
    
    - name: Run validation
      run: just validate-local