name: Windows Validation Extra

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-validation-extra:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup environment
      uses: ./.github/actions/setup-environment
    
    - name: Run extra validation
      run: just validate-extra-local